# Detect underlying system.
ifeq ($(OS),Windows_NT)
	detected_OS := Windows
else
	detected_OS := $(shell sh -c 'uname -s 2>/dev/null || echo not')
endif

# Set proper RM on Windows.
ifeq ($(detected_OS),Windows)
	RMDIR=-rmdir /q /s
	RMFILES=-del /q /s /f
	SEP := $(strip \)
	ENV_SET=cmd /c "set NAPARI_APPLICATION_IPY_INTERACTIVE=0" &&
else
	RMDIR=rm -rf
	RMFILES=rm -rf
	SEP=/
	ENV_SET=NAPARI_APPLICATION_IPY_INTERACTIVE=0
endif

.PHONY: docs clean

SPHINXOPTS =

# Gallery path must be given relative to the docs/ folder

ifeq ($(GALLERY_PATH),)
GALLERY_PATH := ../../napari/examples
endif

mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))
current_dir := $(dir $(mkfile_path))
ifeq ($(detected_OS),Windows)
	current_dir := $(subst /,\,$(current_dir))
endif
docs_dir := $(current_dir)docs

clean:
	echo clean
	echo $(current_dir)
	$(RMDIR) $(docs_dir)$(SEP)_build$(SEP)
	$(RMFILES) $(docs_dir)$(SEP)api$(SEP)napari*.rst
	$(RMFILES) $(docs_dir)$(SEP)gallery$(SEP)*
	$(RMDIR) $(docs_dir)$(SEP)_tags$(SEP)

docs-install:
	python -m pip install -qr $(current_dir)requirements.txt

prep-docs:
	python $(docs_dir)$(SEP)_scripts$(SEP)prep_docs.py

docs-build: prep-docs
	${ENV_SET} sphinx-build -b html docs$(SEP) docs$(SEP)_build -D sphinx_gallery_conf.examples_dirs=$(GALLERY_PATH) $(SPHINXOPTS)

docs-xvfb: prep-docs
	${ENV_SET} xvfb-run --auto-servernum sphinx-build -b html docs$(SEP) docs$(SEP)_build -D sphinx_gallery_conf.examples_dirs=$(GALLERY_PATH) $(SPHINXOPTS)

docs: clean docs-install docs-build

html: clean docs-build

# Implies noplot, but no clean - call 'make clean' manually if needed
# Autogenerated paths need to be ignored to prevent reload loops
html-live: prep-docs
	${ENV_SET} \
	sphinx-autobuild \
		-b html \
		docs$(SEP) \
		docs$(SEP)_build \
		-D plot_gallery=0 \
		-D sphinx_gallery_conf.examples_dirs=$(GALLERY_PATH) \
		--ignore $(docs_dir)"$(SEP)_tags$(SEP)*" \
		--ignore $(docs_dir)"$(SEP)api$(SEP)napari*.rst" \
		--ignore $(docs_dir)"$(SEP)gallery$(SEP)*" \
		--ignore $(docs_dir)"$(SEP)jupyter_execute$(SEP)*" \
		--open-browser \
		--port=0 \
		$(SPHINXOPTS)

html-noplot: clean prep-docs
	${ENV_SET} sphinx-build -D plot_gallery=0 -b html docs$(SEP) docs$(SEP)_build -D sphinx_gallery_conf.examples_dirs=$(GALLERY_PATH) $(SPHINXOPTS)

linkcheck-files:
	${ENV_SET} sphinx-build -b linkcheck -D plot_gallery=0 --color docs$(SEP) docs$(SEP)_build -D sphinx_gallery_conf.examples_dirs=$(GALLERY_PATH)
